apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mes-web
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mes-web
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mes-web
    spec:
      runtimeClassName: {{ .Values.runtimeClassName }}
      tolerations: {{- toYaml .Values.tolerations | nindent 8 }}
      dnsConfig: {{- toYaml .Values.dnsConfig | nindent 8 }}
      containers:
        - name: web
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["node", "services/mes-web/server.js"]
          ports:
            - containerPort: 4000
          env:
            - name: OTEL_SERVICE_NAME
              value: nova-mes-web
            - name: PORT
              value: "4000"
            - name: NOVA_SITE
              value: {{ .Values.novaSite | quote }}
            - name: BATCH_SVC_URL
              value: "http://{{ .Release.Name }}-batch-service.{{ .Release.Namespace }}.svc.cluster.local:4001"
            - name: DISPENSING_SVC_URL
              value: "http://{{ .Release.Name }}-dispensing-service.{{ .Release.Namespace }}.svc.cluster.local:4002"
            - name: RUM_OTLP_TARGET
              value: "http://{{ .Release.Name }}-otel-collector.{{ .Release.Namespace }}.svc.cluster.local:4318"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ if .Values.collector.endpoint }}{{ .Values.collector.endpoint | quote }}{{ else }}"http://{{ .Release.Name }}-otel-collector.{{ .Release.Namespace }}.svc.cluster.local:4318"{{ end }}
            - name: DT_TENANT_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-otel
                  key: dt-tenant-url
            - name: DT_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-otel
                  key: dt-api-token
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mes-web
  namespace: {{ .Release.Namespace }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Release.Name }}-mes-web
  ports:
    - port: 80
      targetPort: 4000
