apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-otel
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  dt-endpoint: {{ .Values.dynatrace.endpoint | quote }}
  dt-api-token: {{ .Values.dynatrace.apiToken | quote }}
  dt-tenant-url: {{ .Values.dynatrace.tenantUrl | quote }}
  otlp-headers: {{ printf "Authorization=Api-Token %s" .Values.dynatrace.apiToken | quote }}
